### ISSUE TITLE
How to generate .d.ts file?

### ISSUE THREAD

**Issue by linonetwo** [SukkaW/rollup-plugin-swc#35]
I have

```ts
import { nodeResolve } from '@rollup/plugin-node-resolve';
import { defineRollupSwcOption, swc } from 'rollup-plugin-swc3';

export default {
  input: 'src/index.ts',
  output: {
    dir: 'dist',
    format: 'es',
  },
  plugins: [
    swc(defineRollupSwcOption({
      sourceMaps: true,
      minify: true,
      jsc: {
        paths: {
          '~services': ['./src/services/index'],
          '~services/*': ['./src/services/*'],
          '~/*': ['./src/*'],
        },
        parser: {
          syntax: 'typescript',
          tsx: false,
          dynamicImport: true,
          decorators: true,
          dts: true,
          importAssertions: false,
        },
        transform: {
          legacyDecorator: true,
          decoratorMetadata: true,
        },
        minify: { sourceMap: true },
        target: 'es2018',
        loose: true,
        externalHelpers: false,
        // Requires v1.2.50 or upper and requires target to be es2016 or upper.
        keepClassNames: true,
      },
      
    })),
    nodeResolve(),
  ],
};

```

And only generates index.js in dist

**Comment by linonetwo** [comment]
You said

> Use rollup-plugin-dts which generates and bundle .d.ts, also does type checking. It is used by this plugin as well.

I thought "used by this plugin" means work out-of-box. But seems I have to call it by myself.

**Comment by linonetwo** [comment]
With dts plugin

```ts
import { nodeResolve } from '@rollup/plugin-node-resolve';
import type { Options as SwcOptions } from '@swc/core';
import fs from 'fs';
import dts from 'rollup-plugin-dts';
import { defineRollupSwcOption, swc } from 'rollup-plugin-swc3';

const swcrc = JSON.parse(fs.readFileSync('../../.swcrc', 'utf8')) as SwcOptions;

export default {
  input: 'src/index.ts',
  output: {
    dir: 'dist',
    format: 'es',
  },
  plugins: [
    swc(defineRollupSwcOption({
      ...swcrc,
      jsc: {
        ...swcrc.jsc,
        paths: {
          '~services': ['./src/services/index'],
          '~services/*': ['./src/services/*'],
          '~/*': ['./src/*'],
        },
      },
    })),
    nodeResolve(),
    dts(),
  ],
};
```

**Comment by ezmiller** [comment]
Yes I'm finding the documentation confusing as well on this topic... Can swc output the the declaration or do we have to rely on another plugin?

**Comment by ezmiller** [comment]
...I had to move back to @rollup/plugins-typescript because I couldn't get the declaration file generation to work here.

**Comment by linonetwo** [comment]
I recently use 

```js
import commonjs from '@rollup/plugin-commonjs';
import json from '@rollup/plugin-json';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import type { Options as SwcOptions } from '@swc/core';
import fs from 'fs';
import path from 'path';
import dts from 'rollup-plugin-dts';
import { defineRollupSwcOption, swc } from 'rollup-plugin-swc3';
import 'rollup';
import { fileURLToPath } from 'node:url';

const swcrc = JSON.parse(fs.readFileSync(path.resolve(fileURLToPath(new URL('.', import.meta.url)), './.swcrc'), 'utf8')) as SwcOptions;

export default [{
  input: 'src/index.ts',
  output: {
    dir: 'dist',
    entryFileNames: '[name].mjs',
    format: 'es',
    preserveModules: true,
    preserveModulesRoot: 'src',
  },
  plugins: [
    swc(defineRollupSwcOption({
      ...swcrc,
    })),
    json(),
    commonjs(),
    nodeResolve({ preferBuiltins: true }),
  ],
}, {
  input: 'src/index.ts',
  output: {
    dir: 'dist',
    format: 'es',
  },
  plugins: [
    json(),
    dts(),
  ],
}];

```

It works for most of the time, but sometimes its type check is different from what I got in VSCode.


It emits error like this, while in VSCode it is clean:

```sh
> rollup --config rollup.config.ts --configPlugin swc3


src/index.ts → dist...
created dist in 91ms

src/index.ts → dist...
src/getNodeAdditionalProperties.ts(15,12): error TS2339: Property 'attributes' does not exist on type 'Partial<TElement>'.
src/getNodeAdditionalProperties.ts(17,5): error TS7053: Element implicitly has an 'any' type because expression of type '"tw-attributes"' can't be used to index type 'Partial<TElement>'.
  Property 'tw-attributes' does not exist on type 'Partial<TElement>'.
src/getNodeAdditionalProperties.ts(27,13): error TS2345: Argument of type 'TElement & { isBlock: boolean; orderedAttributes: IParseTreeAttribute[]; 'tw-attributes': Record<string, IParseTreeAttribute>; }' is not assignable to parameter of type 'Record<string, unknown> | IWikiASTNode'.
  Type 'TElement & { isBlock: boolean; orderedAttributes: IParseTreeAttribute[]; 'tw-attributes': Record<string, IParseTreeAttribute>; }' is not assignable to type 'Record<string, unknown>'.
    Index signature for type 'string' is missing in type 'TElement & { isBlock: boolean; orderedAttributes: IParseTreeAttribute[]; 'tw-attributes': Record<string, IParseTreeAttribute>; }'.

[!] (plugin dts) RollupError: Failed to compile. Check the logs above.
src/getNodeAdditionalProperties.ts
    at error (/Users/linonetwo/Desktop/repo/wikiast/node_modules/.pnpm/registry.npmmirror.com+rollup@3.25.2/node_modules/rollup/dist/shared/rollup.js:349:30)
    at Object.error (/Users/linonetwo/Desktop/repo/wikiast/node_modules/.pnpm/registry.npmmirror.com+rollup@3.25.2/node_modules/rollup/dist/shared/rollup.js:1703:20)
    at Object.error (/Users/linonetwo/Desktop/repo/wikiast/node_modules/.pnpm/registry.npmmirror.com+rollup@3.25.2/node_modules/rollup/dist/shared/rollup.js:25396:42)
    at generateDtsFromTs (file:///Users/linonetwo/Desktop/repo/wikiast/node_modules/.pnpm/rollup-plugin-dts@5.3.0_rollup@3.25.2_typescript@5.1.3/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.mjs:1697:30)
    at Object.transform (file:///Users/linonetwo/Desktop/repo/wikiast/node_modules/.pnpm/rollup-plugin-dts@5.3.0_rollup@3.25.2_typescript@5.1.3/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.mjs:1706:38)
    at /Users/linonetwo/Desktop/repo/wikiast/node_modules/.pnpm/registry.npmmirror.com+rollup@3.25.2/node_modules/rollup/dist/shared/rollup.js:1896:40
```

So I have to abandon `import dts from 'rollup-plugin-dts';` and find other ways, and it should in the doc.

**Comment by linonetwo** [comment]
I use tsc instead:

```
    "build:code": "rollup --config rollup.config.ts --configPlugin swc3",
    "build:type": "tsc --rootDir src --declarationDir dist --project ./tsconfig.json",
```

With tsconfig

```jsonc
{
  "extends": "../../tsconfig.json",
  "include" : ["./src/**/*"],
  "compilerOptions": {
    "rootDir": "./src"
  }
}
```

and base config

```jsonc
{
  "ts-node": {
    "files": true,
    "compilerOptions": {
      "module": "commonjs"
    }
  },
  "compilerOptions": {
    "baseUrl": "./",
    /* Basic Options */
    "target": "ESNext" /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017','ES2018' or 'ESNEXT'. */,
    "module": "ESNext" /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */,
    "lib": ["DOM", "ESNext"] /* Specify library files to be included in the compilation. */,
    "allowJs": true /* Allow javascript/mjs files to be compiled, also apply to mjs in dist, and when running test. */,
    // "checkJs": true,                       /* Report errors in .js files. */
    "jsx": "react-jsx" /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */,
    "declaration": true /* Generates corresponding '.d.ts' file. */,
    "declarationMap": true,                /* Generates a sourcemap for each corresponding '.d.ts' file. */
    "emitDeclarationOnly": true,
    "sourceMap": true /* Generates corresponding '.map' file. */,
    // "outFile": "./",                       /* Concatenate and emit output to single file. */
    "outDir": "dist" /* Redirect output structure to the directory. */,
    // "rootDir": "./src",                       /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */
    // "composite": true,                     /* Enable project compilation */
    // "removeComments": true,                /* Do not emit comments to output. */
    // "noEmit": true,                        /* Do not emit outputs. */
    // "importHelpers": true,                 /* Import emit helpers from 'tslib'. */
    // "downlevelIteration": true,            /* Provide full support for iterables in 'for-of', spread, and destructuring when targeting 'ES5' or 'ES3'. */
    "isolatedModules": true,               /* Transpile each file as a separate module (similar to 'ts.transpileModule'). */
    "verbatimModuleSyntax": false,

    /* Strict Type-Checking Options */
    "strict": true /* Enable all strict type-checking options. */,
    // "noImplicitAny": true,                 /* Raise error on expressions and declarations with an implied 'any' type. */
    "strictNullChecks": true /* Enable strict null checks. */,
    "strictFunctionTypes": true /* Enable strict checking of function types. */,
    "strictPropertyInitialization": true /* Enable strict checking of property initialization in classes. */,
    "noImplicitThis": true /* Raise error on 'this' expressions with an implied 'any' type. */,
    "alwaysStrict": true /* Parse in strict mode and emit "use strict" for each source file. */,

    /* Additional Checks */
    // "noUnusedLocals": true,                /* Report errors on unused locals. */
    // "noUnusedParameters": true,            /* Report errors on unused parameters. */
    // "noImplicitReturns": true,             /* Report error when not all code paths in function return a value. */
    // "noFallthroughCasesInSwitch": true,    /* Report errors for fallthrough cases in switch statement. */

    /* Module Resolution Options */
    "moduleResolution": "node" /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */,
    // "baseUrl": "./",                       /* Base directory to resolve non-absolute module names. */
    // "paths": {},                           /* A series of entries which re-map imports to lookup locations relative to the 'baseUrl'. */
    "rootDirs": ["src"],                        /* List of root folders whose combined content represents the structure of the project at runtime. */
    // "typeRoots": [],                       /* List of folders to include type definitions from. */
    "types": ["node", "tw5-typed", "jest"] /* Type declaration files to be included in compilation. */,
    "allowSyntheticDefaultImports": true /* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "esModuleInterop": true /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */,
    // "preserveSymlinks": true,              /* Do not resolve the real path of symlinks. */

    /* Source Map Options */
    // "sourceRoot": "./",                    /* Specify the location where debugger should locate TypeScript files instead of source locations. */
    // "mapRoot": "./",                       /* Specify the location where debugger should locate map files instead of generated locations. */
    // "inlineSourceMap": true,               /* Emit a single file with source maps instead of having a separate file. */
    // "inlineSources": true,                 /* Emit the source alongside the sourcemaps within a single file; requires '--inlineSourceMap' or '--sourceMap' to be set. */

    /* Experimental Options */
    /* Use ts5 decorators instead https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#decorators */
    "experimentalDecorators": false /* Enables experimental support for ES7 decorators. */,
    "emitDecoratorMetadata": false, /* Enables experimental support for emitting type metadata for decorators. */

    /* Advanced Options */
    "declarationDir": "./dist"                /* Output directory for generated declaration files. */
  }
}
```

**Comment by theIYD** [comment]
@linonetwo I am facing the same issue. Not able to get declaration files out of the box. 

If I use standard `tsc`, it does emit the declaration files. But unfortunately, this fails if you run rollup on watch mode. Are there any other rollup plugins which ONLY emit declaration files and let SWC transpile the code ?

**Comment by linonetwo** [comment]
I use this instead! https://github.com/Swatinem/rollup-plugin-dts/discussions/207#discussioncomment-6889021
